# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import publisher.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sponsor', '__first__'),
        ('campaign', '0001_initial'),
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Publisher Name')),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='Contact Name')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=80, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='State')),
                ('telephone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telephone')),
                ('email', models.EmailField(blank=True, max_length=75, null=True, unique=True)),
                ('logo', models.FileField(blank=True, upload_to=publisher.models.get_publisher_logo_path, verbose_name='Upload Logo')),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('password', models.CharField(max_length=128)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Country')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.Industry')),
                ('sponsor', models.ManyToManyField(to='sponsor.Sponsor')),
            ],
            options={
                'db_table': 'publisher_publisher',
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=100, verbose_name='Website Name')),
                ('website_domain', models.URLField(max_length=100, verbose_name='Website Domain')),
                ('website_logo', models.FileField(blank=True, upload_to=publisher.models.get_website_logo_path, verbose_name='Upload Logo')),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook_page', models.CharField(blank=True, max_length=100, null=True)),
                ('avg_page_views', models.PositiveIntegerField(blank=True, null=True)),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.Industry')),
            ],
            options={
                'db_table': 'publisher_website',
            },
        ),
        migrations.AddField(
            model_name='publisher',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website', to='publisher.Website'),
        ),
    ]
