# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 18:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='email',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='id',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='name',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='password',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='token',
        ),
        migrations.AddField(
            model_name='publisher',
            name='myuser_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publisher',
            name='logo',
            field=models.ImageField(blank=True, upload_to=b'', verbose_name='Upload Logo'),
        ),
    ]
