# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0002_auto_20151217_1217'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='publisher',
            table=None,
        ),
    ]
