# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0006_auto_20151217_1351'),
        ('publisher', '0004_auto_20151217_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='sponsor',
            field=models.ManyToManyField(to='sponsor.Sponsor'),
        ),
    ]
