# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0005_publisher_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='core.Country'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='sponsor',
            field=models.ManyToManyField(related_name='sponsor', to='sponsor.Sponsor'),
        ),
    ]
