# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0007_auto_20151217_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='city',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publisher',
            name='state',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='State'),
            preserve_default=False,
        ),
    ]
