# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0009_auto_20151220_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publishers', to='core.Country'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='sponsor',
            field=models.ManyToManyField(blank=True, related_name='publishers', to='sponsor.Sponsor'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='website',
            field=models.ManyToManyField(blank=True, related_name='publishers', to='publisher.Website'),
        ),
    ]
