# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_industry_type'),
        ('publisher', '0010_auto_20151220_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='industry',
        ),
        migrations.AddField(
            model_name='website',
            name='industry',
            field=models.ManyToManyField(blank=True, to='campaign.Industry'),
        ),
    ]
