# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import publisher.models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0011_auto_20151221_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='website_logo',
            field=models.ImageField(blank=True, upload_to=publisher.models.get_website_logo_path, verbose_name='Upload Logo'),
        ),
    ]
