# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0012_auto_20151221_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='is_verified',
            field=models.NullBooleanField(default=False),
        ),
    ]
