# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0013_website_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
