# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0015_publisher_is_completed_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='website',
        ),
        migrations.AddField(
            model_name='publisher',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publishers', to='publisher.Website'),
        ),
    ]
