# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0017_auto_20151228_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='is_completed_auth',
            field=models.CharField(choices=[(b'advertisers', b'advertisers'), (b'add_website', b'Add website'), (b'get_code', b'Get code'), (b'completed', b'Register complete')], default=b'advertisers', max_length=100, verbose_name='Complete join network stage'),
        ),
    ]
