# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sponsor', '0001_initial'),
        ('publisher', '0002_auto_20151217_1217'),
        ('campaign', '0002_auto_20151217_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignNotifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publisher.Publisher')),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sponsor.Sponsor')),
            ],
        ),
        migrations.CreateModel(
            name='CouponNotifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('day', models.IntegerField(default=1)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publisher.Publisher')),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sponsor.Sponsor')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date_created', models.DateField()),
                ('notify_type', models.CharField(max_length=20)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publisher.Publisher')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsor.Sponsor')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_reference', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('notify_type', models.CharField(max_length=20)),
                ('sent_status', models.CharField(max_length=20)),
                ('reject_reason', models.TextField()),
                ('day_left', models.IntegerField()),
                ('date_created', models.DateField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publisher.Publisher')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsor.Sponsor')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publisher.Website')),
            ],
        ),
        migrations.CreateModel(
            name='RedeemCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeem_on', models.DateTimeField()),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publisher.Publisher')),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sponsor.Sponsor')),
            ],
        ),
        migrations.CreateModel(
            name='SaveReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_part', models.CharField(max_length=200)),
                ('saved_on', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publisher.Publisher')),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sponsor.Sponsor')),
            ],
        ),
        migrations.CreateModel(
            name='SocialShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_type', models.CharField(blank=True, max_length=20, null=True)),
                ('reference_url', models.CharField(max_length=256)),
                ('date_created', models.DateField()),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publisher.Publisher')),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sponsor.Sponsor')),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_url', models.CharField(max_length=256)),
                ('token', models.CharField(max_length=100)),
                ('day', models.IntegerField(default=0)),
                ('dollar_saved', models.IntegerField(default=0)),
                ('created', models.DateTimeField()),
                ('last_viewed', models.DateField(blank=True, null=True)),
                ('last_saved', models.DateField(blank=True, null=True)),
                ('is_redeemed', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('notify_me', models.NullBooleanField(default=False)),
                ('agreed', models.NullBooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign')),
                ('website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publisher.Website')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Widget')),
            ],
        ),
        migrations.AddField(
            model_name='socialshare',
            name='usertoken',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.UserToken'),
        ),
        migrations.AddField(
            model_name='socialshare',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publisher.Website'),
        ),
        migrations.AddField(
            model_name='socialshare',
            name='widget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.Widget'),
        ),
        migrations.AddField(
            model_name='savereward',
            name='usertoken',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.UserToken'),
        ),
        migrations.AddField(
            model_name='savereward',
            name='widget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.Widget'),
        ),
        migrations.AddField(
            model_name='redeemcoupon',
            name='usertoken',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.UserToken'),
        ),
        migrations.AddField(
            model_name='redeemcoupon',
            name='widget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.Widget'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='usertoken',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.UserToken'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publisher.Website'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Widget'),
        ),
        migrations.AddField(
            model_name='couponnotifier',
            name='usertoken',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.UserToken'),
        ),
        migrations.AddField(
            model_name='couponnotifier',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publisher.Website'),
        ),
        migrations.AddField(
            model_name='couponnotifier',
            name='widget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.Widget'),
        ),
        migrations.AddField(
            model_name='campaignnotifier',
            name='usertoken',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.UserToken'),
        ),
        migrations.AddField(
            model_name='campaignnotifier',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publisher.Website'),
        ),
        migrations.AddField(
            model_name='campaignnotifier',
            name='widget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.Widget'),
        ),
    ]
