# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 17:28
from __future__ import unicode_literals

import campaign.models
import colorful.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=100, verbose_name='Campaign Name')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('image', models.FileField(upload_to=campaign.models.get_campaign_image_path, verbose_name='Image')),
                ('color', colorful.fields.RGBColorField(max_length=7)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('coupons_available', models.IntegerField(default=0, verbose_name='Coupons Available')),
                ('landing_url', models.URLField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'campaign_campaign',
            },
        ),
        migrations.CreateModel(
            name='CampaignTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('reference_url', models.CharField(max_length=100, verbose_name='Reference Website')),
                ('reference_token', models.CharField(max_length=100, verbose_name='Reference Token')),
                ('clicked_on', models.DateTimeField()),
                ('action', models.CharField(choices=[(b'vd', b'Viewed'), (b'cd', b'Clicked')], max_length=4)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign')),
            ],
            options={
                'db_table': 'campaign_campaigntracker',
            },
        ),
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_type', models.CharField(max_length=100, verbose_name='Industry')),
            ],
            options={
                'db_table': 'campaign_industry',
                'verbose_name_plural': 'Industries',
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_name', models.CharField(max_length=100, verbose_name='Widget Name')),
                ('embed_code', models.TextField(blank=True, default=b'', null=True, verbose_name='Embedded Code')),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign')),
            ],
            options={
                'db_table': 'campaign_widget',
            },
        ),
    ]
