# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sponsor', '__first__'),
        ('campaign', '0001_initial'),
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigntracker',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publisher.Publisher'),
        ),
        migrations.AddField(
            model_name='campaigntracker',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sponsor.Sponsor'),
        ),
        migrations.AddField(
            model_name='campaigntracker',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publisher.Website'),
        ),
        migrations.AddField(
            model_name='campaigntracker',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.Widget'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publisher.Publisher'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsor.Sponsor'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publisher.Website'),
        ),
    ]
