# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_auto_20151217_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='type',
            field=models.CharField(choices=[(b'default', b'Default'), (b'sub', b'Sub')], default=b'default', max_length=100, verbose_name='Category type'),
        ),
    ]
