# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sponsor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sponsor Name')),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='Contact Name')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telephone')),
                ('email', models.EmailField(blank=True, max_length=75, verbose_name='Email')),
                ('logo', models.FileField(blank=True, upload_to=sponsor.models.get_sponsor_logo_path, verbose_name='Upload Logo')),
                ('token', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('password', models.CharField(max_length=128)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Country')),
            ],
            options={
                'db_table': 'sponsor_sponsor',
            },
        ),
        migrations.CreateModel(
            name='SponsorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Sponsor Type')),
            ],
            options={
                'db_table': 'sponsor_type',
            },
        ),
        migrations.AddField(
            model_name='sponsor',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsor.SponsorType'),
        ),
    ]
