# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import sponsor.models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0002_auto_20151217_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(blank=True, upload_to=sponsor.models.get_sponsor_logo_path, verbose_name='Upload Logo'),
        ),
    ]
