# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0003_auto_20151217_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(blank=True, upload_to=b'', verbose_name='Upload Logo'),
        ),
    ]
