# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0005_auto_20151217_1349'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sponsor',
            table='sponsor_sponsor',
        ),
    ]
