# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('sponsor', '0008_auto_20151217_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='country',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(blank=True, upload_to=b'', verbose_name='Upload Logo'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telephone'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sponsor.SponsorType'),
            preserve_default=False,
        ),
    ]
