# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_auto_20151217_1128'),
        ('sponsor', '0009_auto_20151217_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='industry',
            field=models.ManyToManyField(blank=True, null=True, to='campaign.Industry'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Country'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telephone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sponsor.SponsorType'),
        ),
    ]
