# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0011_auto_20151221_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='myuser_ptr',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
