# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0012_auto_20151224_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name'),
        ),
    ]
